spring.application.name=pdd-ai

spring.datasource.url=jdbc:postgresql://localhost:5432/pdd_db
spring.datasource.username=pdd_admin
spring.datasource.password=gbyudby
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

import.questions.file=classpath:questions.json

jwt.secret=mySecretKeyForJwtToken1234567890!@#$
jwt.expiration=86400000